version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./uploads:/var/www/app/uploads
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 6001:6001
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
    ports:
      - 3306:3306
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80
    networks:
      - laravel_network

networks:
  laravel_network:
